### ISSUE TITLE
Issue with lockfileVersion == 3

### ISSUE THREAD

**Issue by MarkSpencerTan** [kiegroup/lock-treatment-tool#108]
Has anyone used this tool before with projects that have a package-lock.json that has a lockfile version = 3? I'm getting an error running the 'locktt' command below when my lockfile version is 3. lockfileVersion 1 and 2 seems to be ok.

lockfile version 3:

```bash
# locktt --registry=`npm config get registry`   
Treating fields...
/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/@kie/lock-treatment-tool/lib/treat-locks/npm.lock.js:29
  Object.keys(dependencies).forEach((prop) => {
         ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at treatFields (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/@kie/lock-treatment-tool/lib/treat-locks/npm.lock.js:29:10)
    at treatLockFields (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/@kie/lock-treatment-tool/lib/treat-locks/npm.lock.js:61:5)
    at run (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/@kie/lock-treatment-tool/lib/treat-locks/npm.lock.js:74:21)
    at run (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/@kie/lock-treatment-tool/script/treat-lock-files.js:101:3)
    at Object.<anonymous> (/Users/tanm2/.nvm/versions/node/v18.15.0/lib/node_modules/@kie/lock-treatment-tool/bin/locktt.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
```

NPM version: 9.5.0
Node version: v18.15.0

**Comment by MarkSpencerTan** [comment]
comparing the v2 and v3 lockfiles, looks like they removed the root level "dependencies" block, which causes the null dependencies variable in the `Object.keys(dependencies).forEach(...)` call

I think it could be useful to have a check if that dependencies variable is not null before doing the forEach loop

**Comment by MarkSpencerTan** [comment]
looks like I was using an older version, latest works :)
